volumes:
 datafiles:

services:
  exercise-api:
    image: ${DOCKER_REGISTRY-}exerciseapi
    build:
      context: .
      dockerfile: /Exercises/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MYSQL_HOST=exercise-db
      - MYSQL_PORT=3306
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=password
    ports:
      - 3001:8080

  exercise-db:
    image: mysql/mysql-server:8.0.23
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - datafiles:/var/lib/mysql
      - ./Exercises/db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
    restart: always
    ports:
      - 3307:3306
    build:
      context: .
    command: --init-file /docker-entrypoint-initdb.d/db-init.sql
    tmpfs:
      - /var/lib/mysql